Repository floating/frame, pull requests merged in 2022-12, with the labels that each got.

#1212 Formatting (config only)
  .husky/pre-commit
  .husky/pre-push
  .prettierignore
  .prettierrc.json
  package-lock.json
  package.json
Labels: dependencies, tooling

#1253 fix tx footer alignment and bg
  app/App/Account/Account/Requests/style/index.styl
Labels: styling

#1262 add instance id
  dash/App/Chains/style/index.styl
  dash/App/Main/index.js
Labels: enhancement

#1271 display coin balance with amount first
  app/App/Account/Account/Requests/TransactionRequest/TxAction/index.js
  app/App/Account/Account/Requests/TransactionRequest/TxFeeNew/index.js
  resources/Components/DisplayValue/index.js
  resources/utils/displayValue.ts
  test/resources/Components/DisplayValue/index.test.js
Labels: maintenance, UX

#1269 tx flows and ui polish
  app/App/Account/Account/Balances/BalancesExpanded/index.js
  app/App/Account/Account/Balances/BalancesPreview/index.js
  app/App/Account/Account/Balances/style/index.styl
  app/App/Account/Account/Inventory/InventoryExpanded/index.js
  app/App/Account/Account/Inventory/InventoryPreview/index.js
  app/App/Account/Account/Inventory/style/index.styl
  app/App/Account/Account/Permissions/DappsExpanded/index.js
  app/App/Account/Account/Permissions/DappsPreview/index.js
  app/App/Account/Account/Permissions/style/index.styl
  app/App/Account/Account/Requests/TransactionRequest/TxMain/style/index.styl
  app/App/Account/Account/Requests/TransactionRequest/TxMainNew/overview.js
  app/App/Account/Account/Requests/TransactionRequest/index.js
  app/App/Account/Account/Requests/TransactionRequest/style/new.styl
  app/App/Account/Account/Requests/index.js
  app/App/Account/Account/Requests/style/index.styl
  app/App/Account/Account/index.js
  app/App/Account/Account/style/index.styl
  app/App/Account/Account/style/view.styl
  dash/App/Chains/style/index.styl
  dash/App/Dapps/index.js
  dash/App/Dapps/style/index.styl
  dash/App/Main/index.js
  dash/App/Main/style/index.styl
  dash/App/Settings/index.js
  dash/App/Signer/style/index.styl
  main/accounts/Account/index.ts
  resources/Components/Cluster/index.js
  resources/Components/DisplayValue/style/index.styl
  resources/Components/RequestItem/index.js
  resources/Components/RequestItem/style/index.styl
  resources/Components/RingIcon/index.js
  resources/Components/RingIcon/index.styl
  resources/base.styl
Labels: UX

#1261 Aragone
  @types/@aragon__wrapper/index.d.ts
  @types/frame/state.d.ts
  app/App/Account/Account/Settings/SettingsExpanded/index.js
  app/App/Account/Account/Signer/SignerPreview/index.js
  app/App/Account/Account/Verify/index.js
  app/App/Account/Account/index.js
  app/App/AccountSelector/AccountController/index.js
  app/App/Notify/index.js
  app/index.js
  dash/App/Accounts/Add/AddAragon/index.js
  dash/App/Accounts/Add/AddGnosisSafe/index.js
  dash/App/Accounts/Add/index.js
  dash/App/Accounts/Add/style/index.styl
  dash/App/Accounts/index.js
  dash/App/Command/index.js
  dash/App/Signer/index.js
  flow/App/index.js
  flow/svg/index.js
  main/accounts/Account/index.ts
  main/accounts/aragon/appNames.ts
  main/accounts/aragon/index.ts
  main/accounts/index.ts
  main/provider/index.ts
  main/rpc/index.js
  main/store/actions/index.js
  main/store/migrations/index.js
  main/store/state/index.js
  main/windows/window.ts
  package-lock.json
  package.json
  resources/domain/signer/index.ts
  resources/svg/index.js
  test/__mocks__/fs.js
  test/main/store/migrations/index.test.js
  test/main/store/state/index.test.js
Labels: dependencies, smart accounts, WIP, maintenance

#1277 Show unknown fee
  app/App/Account/Account/Requests/TransactionRequest/TxAction/index.js
  app/App/Account/Account/Requests/TransactionRequest/TxFeeNew/index.js
  app/App/Account/Account/Requests/TransactionRequest/TxMain/index.js
  test/app/App/Account/Account/Requests/TransactionRequest/TxFeeNew/index.test.js
Labels: bug, transactions

#1189 System Tray rework
  main/index.ts
  main/windows/index.ts
  main/windows/systemTray.ts
Labels: enhancement, WIP, maintenance, UX

#1282 C11 ui polish
  app/tray/Account/Account/Balances/style/index.styl
  app/tray/Account/Account/Inventory/style/index.styl
  app/tray/Account/Account/Requests/TransactionRequest/TxFeeNew/index.js
  app/tray/Account/Account/Requests/TransactionRequest/TxFeeNew/style/index.styl
  app/tray/Account/Account/Requests/index.js
  app/tray/Account/Account/Settings/SettingsPreview/index.js
  app/tray/Account/Account/Signer/style/index.styl
  resources/base.styl
  resources/utils/displayValue.ts
  test/app/Tray/Account/Account/Requests/TransactionRequest/TxFeeNew/index.test.js
Labels: UX, styling

#1281 Multiscreen summon
  main/windows/index.ts
  main/windows/systemTray.ts
Labels: UX

#1274 Seed Phrase & password input validations
  app/dash/Accounts/Add/AddPhrase/index.js
  app/dash/Accounts/Add/AddRing/index.js
  app/dash/Accounts/Add/style/index.styl
  app/dash/Accounts/index.js
  dash/App/Accounts/Add/Components/index.js
  resources/Components/Password/index.js
  test/dash/App/Accounts/Add/AddPhrase/index.test.js
  test/dash/App/Accounts/Add/AddRing/index.test.js
  test/resources/Components/Password/index.test.js
Labels: hot signers, UX

#1283 fix workspaces dash show
  main/windows/index.ts
  main/windows/systemTray.ts
Labels: bug

#1289 Fix top level HMR
  app/dapp/index.js
  app/dash/index.js
  app/onboard/index.js
  app/tray/index.js
Labels: bug, tooling

#1288 c11 ux updates/fixes and onboarding
  app/dash/Accounts/Add/Components/index.js
  app/dash/Accounts/Add/style/index.styl
  app/dash/Accounts/index.js
  app/dash/Main/style/index.styl
  app/dash/index.styl
  app/onboard/App/Slides/Access/index.jsx
  app/onboard/App/Slides/Accounts/index.jsx
  app/onboard/App/Slides/Chains/index.jsx
  app/onboard/App/Slides/Extension/index.jsx
  app/onboard/App/Slides/Intro/index.jsx
  app/onboard/App/Slides/Outro/index.jsx
  app/onboard/App/index.jsx
  app/onboard/App/styled/index.jsx
  app/tray/Account/Account/Balances/style/index.styl
  app/tray/Account/Account/Inventory/style/index.styl
  app/tray/Account/Account/Requests/index.js
  main/windows/index.ts
  package.json
  resources/Components/Dropdown/index.styl
  resources/Components/Password/index.js
  resources/base.styl
  test/resources/Components/Password/index.test.js
Labels: UX, onboarding

#1305 Script updates
  scripts/run-dev.js
Labels: tooling
