Repository floating/frame, pull requests merged in 2023-01, with the labels that each got.

#1308 enable react devtools
  electron-builder.json
  main/dev/cpu.ts
  main/dev/extensions.ts
  main/dev/index.ts
  main/index.ts
  package-lock.json
  package.json
  resources/bridge/index.js
  resources/link/index.js
Labels: tooling

#1325 Fix react key warnings
  app/tray/Account/Account/Activity/index.js
  app/tray/Account/Account/Balances/BalancesExpanded/index.js
  app/tray/Account/Account/Balances/BalancesPreview/index.js
  app/tray/Account/Account/Permissions/DappsExpanded/index.js
  app/tray/Account/Account/Permissions/DappsPreview/index.js
Labels: bug, maintenance

#1335 Arm64 linux builds
  electron-builder.json
Labels: linux, tooling

#1334 component tests refactor
  app/tray/Account/Requests/TransactionRequest/TokenSpend/index.js
  resources/Components/Cluster/index.js
  test/app/dash/Accounts/Add/AddAddress/index.test.js
  test/app/dash/Accounts/Add/AddPhrase/index.test.js
  test/app/dash/Accounts/Add/AddRing/index.test.js
  test/app/dash/Chains/Chain/add.test.js
  test/app/dash/Chains/Chain/expand.test.js
  test/app/dash/Tokens/AddToken/index.test.js
  test/app/onboard/App/Slides/Proceed/index.test.js
  test/app/tray/Account/Requests/TransactionRequest/AdjustFee/index.test.js
  test/app/tray/Account/Requests/TransactionRequest/TokenSpend/index.test.js
  test/app/tray/Account/Requests/TransactionRequest/TxFee/index.test.js
  test/app/tray/Account/Requests/TransactionRequest/index.test.js
  test/componentSetup.js
  test/resources/Components/Confirm/index.test.js
  test/resources/Components/DisplayValue/index.test.js
  test/resources/Components/Password/index.test.js
Labels: maintenance, testing

#1343 Fix Trezor T typed data signing
  main/signers/trezor/Trezor/index.ts
Labels: bug, hardware signers, trezor

#1344 show specific error when failing strict Trezor safety checks
  main/signers/trezor/Trezor/index.ts
Labels: bug, hardware signers, trezor

#1342 Upgrade trezor
  main/signers/trezor/Trezor/index.ts
  main/signers/trezor/adapter.ts
  main/signers/trezor/bridge.ts
  package-lock.json
  package.json
  test/main/signers/trezor/bridge.test.js
Labels: dependencies, hardware signers, trezor

#1332 fix signer display type for watch accounts
  main/store/migrations/index.js
  test/main/store/migrations/index.test.js
Labels: bug, watch accounts

#1352 Disallow editing approval amount after request has been submitted
  app/tray/Account/Requests/TransactionRequest/TxAction/index.js
Labels: UX

#1349 Canary 13 UX
  app/tray/Account/Requests/index.js
  app/tray/Account/Requests/style/index.styl
  app/tray/AccountSelector/AccountController/style/index.styl
  app/tray/AccountSelector/style/index.styl
  app/tray/Footer/RequestCommand/index.js
  main/accounts/Account/index.ts
  main/accounts/index.ts
  main/index.ts
  resources/base.styl
  test/main/accounts/index.test.js
Labels: UX, styling

#1356 fix React key errors
  app/dash/Accounts/Add/AddHardware/index.js
  app/dash/Chains/index.js
  app/dash/Dapps/DappDetails/index.js
  app/dash/Dapps/index.js
  app/dash/Tokens/CustomTokens/index.js
  app/tray/Account/Requests/TransactionRequest/TxMainNew/overview.js
Labels: bug, maintenance

#1345 Render accounts if signer disconnected when in expanded view
  app/dash/App.js
  main/signers/index.ts
  main/store/actions/index.js
  test/main/store/actions/index.test.js
Labels: bug, hardware signers, UX

#1361 Remove compile before test
  package.json
  test/main/signers/hot/RingSigner/index.test.js
  test/main/signers/hot/SeedSigner/index.test.js
Labels: maintenance, testing

#1358 Fix add chain request navigation
  app/dash/Chains/Chain/ChainNew/index.js
  app/dash/Chains/Chain/index.js
  main/store/actions/index.js
Labels: UX, navigation

#1357 prompt user for permission to connect from Firefox extension
  app/tray/Notify/ExtensionConnect/index.jsx
  app/tray/Notify/index.js
  main/accounts/types.ts
  main/api/origins.ts
  main/api/ws.ts
  main/rpc/index.js
  main/store/actions/index.js
  main/store/state/index.js
  resources/Components/Cluster/style/index.styl
  test/main/api/origins.test.js
Labels: security

#1364 call tray readyHandler only once
  main/windows/index.ts
Labels: bug, system tray

#1365 open block explorer from chains panel
  app/dash/Chains/Chain/ChainExpanded/index.js
  app/dash/Chains/Chain/ChainPreview/index.js
  app/dash/Chains/Chain/Components/index.js
  app/dash/Chains/Chain/index.js
  app/dash/Chains/Chain/style/index.styl
  app/dash/Chains/style/index.styl
  app/dash/Notify/index.js
  app/tray/Footer/RequestCommand/index.js
  app/tray/Notify/index.js
  app/tray/Notify/style/index.styl
  main/accounts/index.ts
  main/index.ts
  main/rpc/index.js
  main/windows/window.ts
  resources/svg/index.js
Labels: enhancement, chains

#1367 Fixes for various footer issues, tx step descriptions
  app/tray/Account/Requests/style/index.styl
  app/tray/Footer/RequestCommand/TxBar/index.js
  app/tray/Footer/RequestCommand/index.js
Labels: UX, styling

#1362 add slide explaining how to switch chains
  app/onboard/App/Slides/Hardware/index.jsx
  app/onboard/App/Slides/Omnichain/index.jsx
  app/onboard/App/Slides/SwitchChains/chainswitch.mp4
  app/onboard/App/Slides/SwitchChains/index.jsx
  app/onboard/App/Slides/index.jsx
  app/onboard/App/styled/index.jsx
Labels: onboarding

#1363 Fix approval overlap
  app/tray/Account/Requests/TransactionRequest/TokenSpend/index.js
  app/tray/Account/Requests/TransactionRequest/TokenSpend/style/index.styl
Labels: styling

#1382 Fix black screen when running prod
  app/tray/Account/Requests/SignPermitRequest/index.js
  app/tray/Account/Requests/SignTypedDataRequest/index.js
  resources/Components/SimpleTypedData/index.js
Labels: bug

#1380 fix workspace and mouse click issues on MacOS
  main/windows/index.ts
  main/windows/window.ts
Labels: mac, window management
