Repository floating/frame, pull requests merged in 2023-02, with the labels that each got.

#1381 Update deps
  jest.config.json
  package-lock.json
  package.json
Labels: dependencies

#1350 Add Keystore Account rework
  app/dash/Accounts/Add/AddKeystore/index.js
  app/dash/Accounts/Add/Components/index.js
  app/dash/Accounts/index.js
  main/rpc/index.js
  resources/Components/Password/index.js
  test/app/dash/Accounts/Add/AddKeystore/index.test.js
  test/app/dash/Accounts/Add/AddPhrase/index.test.js
  test/app/dash/Accounts/Add/AddRing/index.test.js
  test/componentSetup.js
Labels: maintenance, UX

#1369 Show correct summon shortcut
  app/dash/Settings/index.js
  app/onboard/App/Slides/Access/index.jsx
  resources/app/index.js
Labels: WIP, accessibility, window management

#1405 initial chain monitor, cluster chains panel
  app/dash/Chains/Chain/ChainExpanded/index.js
  app/dash/Chains/Chain/ChainPreview/index.js
  app/dash/Chains/Chain/Components/index.js
  app/dash/Chains/Chain/Connection/index.js
  app/dash/Chains/style/index.styl
  app/tray/Account/Account.js
  app/tray/Account/Chains/ChainsPreview/index.js
  app/tray/Account/Chains/index.js
  app/tray/Account/Chains/style/index.styl
  app/tray/Account/style/account.styl
  app/tray/Account/style/index.styl
  main/index.ts
  main/store/state/index.js
  main/windows/window.ts
  resources/Components/FooterAux/index.js
  resources/Components/Monitor/index.js
  resources/Components/Monitor/style/index.styl
  resources/Components/index.styl
Labels: UX
