Repository floating/frame, pull requests merged in 2023-03, with the labels that each got.

#1468 Migrations: ensure native currency names & symbols
  main/store/migrations/index.js
  test/main/store/migrations/index.test.js
Labels: bug, store migration

#1472 Fix windows glide
  main/windows/index.ts
Labels: bug, windows, window management

#1476 ensure chain exists in networksMeta
  main/store/migrations/index.js
  test/main/store/migrations/index.test.js
Labels: store migration

#1475 disable explorer btn on tx when no explorer
  app/tray/Account/Requests/style/index.styl
  app/tray/Footer/RequestCommand/index.js
Labels: UX, transactions

#1337 Linting
  .babelrc.json
  .eslintrc.json
  eslint.config.mjs
  package-lock.json
  package.json
  tsconfig.build.json
  tsconfig.json
Labels: dependencies, tooling, maintenance, linting

#1480 update deps
  .github/workflows/build.yml
  .github/workflows/canary.yml
  .github/workflows/compile-and-test.yml
  README.md
  package-lock.json
  package.json
Labels: dependencies

#1484 fix broken images in balances & inventory
  app/tray/Account/Balances/style/index.styl
  app/tray/Account/Inventory/InventoryCollection/index.js
  app/tray/Account/Inventory/style/index.styl
  resources/Components/RingIcon/index.js
Labels: UX, balances, inventory

#1492 fix dev script - spawn using shell in Windows
  scripts/run-dev.mjs
Labels: bug, windows, tooling

#1493 fix prod build
  package-lock.json
  package.json
Labels: bug, tooling

#1487 Update README for 0.6.x
  README.md
  asset/png/FrameExample0-6-3.png
Labels: documentation

#1499 Add "processing" to add hot signer flow
  app/dash/Accounts/Add/Components/index.js
  app/dash/Accounts/Add/style/index.styl
  resources/Components/Password/index.js
Labels: hot signers, UX
